const categoryStructure = {
  "Living Room": [
    "Sofas",
    "Coffee Tables",
    "TV Stands",
    "Accent Chairs",
    "Console Tables",
    "Sectional Sofas",
    "Livingroom Packages",
    "Tables",
    "Nest of Tables",
    "Semi Recliners",
    "Couches in set",
    "Buffet Tables",
    "Pouffes & Ottomans",
  ],
  Bedroom: [
    "Beds",
    "Dressers",
    "Nightstands",
    "Wardrobes",
    "Mattresses",
    "Ottomans",
    "Chest of Drawers",
    "Bedroom Packages",
    "Bed Benches",
  ],
  "Dining Room": [
    "Dining Tables",
    "Dining Chairs",
    "Buffets",
    "Bar Carts",
    "China Cabinets",
    "Four seater DIning Sets",
    "Six seater DIning Sets",
    "Eight seater DIning Sets",
  ],
  Office: [
    "Desks",
    "Office Chairs",
    "Bookshelves",
    "Filing Cabinets",
    "Desk Lamps",
  ],
  Outdoor: [
    "Patio Sets",
    "Outdoor Chairs",
    "Garden Benches",
    "Hammocks",
    "Outdoor Tables",
  ],
  Storage: [
    "Cabinets",
    "Shelving",
    "Storage Bins",
    "Closet Systems",
    "Media Storage",
  ],
  Decor: [
    "Mirrors",
    "Mirror Frames",
    "Rugs",
    "Lighting",
    "Wall Art",
    "Throw Pillows",
  ],
  "kids Room": ["Beds", "Double Deckers", "Baby Cots"],
  Matresses: [
    "Foam Matresses",
    "Spring Matresses",
    "Orthopedic Matresses",
    "Memory Foam Matresses",
  ],
};
